# Generated by Django 2.1.1 on 2019-01-07 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('registration_token', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserWebSocketActivity',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
